/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPackage;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author LENOVO LOQ
 */
public class checkOutFrame extends javax.swing.JFrame {

    /**
     * Creates new form checkOutFrame
     */
    public checkOutFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        borobudurButton = new javax.swing.JRadioButton();
        kutaButton = new javax.swing.JRadioButton();
        bromoButton = new javax.swing.JRadioButton();
        tobaButton = new javax.swing.JRadioButton();
        sortPopuler = new javax.swing.JButton();
        sortHarga = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        pesanButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jmlTiketSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notaArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        keluar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        cariButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        header.setBackground(new java.awt.Color(25, 133, 161));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/JelajahKu Header.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        buttonGroup1.add(borobudurButton);
        borobudurButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        borobudurButton.setForeground(new java.awt.Color(69, 69, 69));
        borobudurButton.setText("Candi Borobudur  @Rp75000");
        borobudurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borobudurButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(kutaButton);
        kutaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kutaButton.setForeground(new java.awt.Color(69, 69, 69));
        kutaButton.setText("Pantai Kuta @Rp50000");
        kutaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kutaButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(bromoButton);
        bromoButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bromoButton.setForeground(new java.awt.Color(69, 69, 69));
        bromoButton.setText("Gunung Bromo @Rp80000");

        buttonGroup1.add(tobaButton);
        tobaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tobaButton.setForeground(new java.awt.Color(69, 69, 69));
        tobaButton.setText("Danau Toba @Rp60000");

        sortPopuler.setText("Urut Populer");
        sortPopuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortPopulerActionPerformed(evt);
            }
        });

        sortHarga.setText("Urut Harga");
        sortHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortHargaActionPerformed(evt);
            }
        });

        backButton.setText("Kembali");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        pesanButton.setText("Selesai");
        pesanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 69, 69));
        jLabel2.setText("Jumlah Tiket");

        jmlTiketSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 133, 161));
        jLabel3.setText("Finalilasi Pesanan");

        notaArea.setColumns(20);
        notaArea.setRows(5);
        jScrollPane1.setViewportView(notaArea);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 69, 69));
        jLabel4.setText("Nota Pembelian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sortPopuler)
                        .addGap(18, 18, 18)
                        .addComponent(sortHarga))
                    .addComponent(tobaButton)
                    .addComponent(bromoButton)
                    .addComponent(kutaButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(borobudurButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jmlTiketSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(95, 95, 95)
                            .addComponent(jLabel2)))
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(638, 638, 638))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pesanButton)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borobudurButton)
                            .addComponent(jmlTiketSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kutaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bromoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tobaButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sortPopuler)
                            .addComponent(sortHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(pesanButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Menu");

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu1.add(keluar);

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        cariButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cariButton.setText("Search");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });
        jMenu1.add(cariButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new LogRegFrame().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        String[] wisata = {"pantai kuta", "kuta",
            "gunung bromo", "bromo",
            "candi borobudur", "borobudur",
            "danau toba", "toba"};

        String cariWisata = JOptionPane.showInputDialog(this, "Masukkan wisata yang ingin dicari");

        if (cariWisata == null || cariWisata.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi kolom.");
            return;
        }

        String temu = "";

        for (int i = 0; i < wisata.length; i++) {
            if (cariWisata.equalsIgnoreCase(wisata[i])) {
                temu = wisata[i];
                break;
            }
        }

        if (temu.equalsIgnoreCase(wisata[0]) || temu.equalsIgnoreCase(wisata[1])) {
            new kutaFrame().setVisible(true);
            this.setVisible(false);
        } else if (temu.equalsIgnoreCase(wisata[2]) || temu.equalsIgnoreCase(wisata[3])) {
            new bromoFrame().setVisible(true);
            this.setVisible(false);
        } else if (temu.equalsIgnoreCase(wisata[4]) || temu.equalsIgnoreCase(wisata[5])) {
            new borobudurFrame().setVisible(true);
            this.setVisible(false);
        } else if (temu.equalsIgnoreCase(wisata[6]) || temu.equalsIgnoreCase(wisata[7])) {
            new tobaFrame().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Maaf wisata yang Anda cari tidak dapat ditemukan.");
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void borobudurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borobudurButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borobudurButtonActionPerformed

    private void kutaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kutaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kutaButtonActionPerformed

    private void sortPopulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortPopulerActionPerformed
        String[] nama = {"Candi Borobudur", "Pantai Kuta", "Gunung Bromo", "Danau Toba"};
        int[] harga = {75000, 50000, 80000, 60000};
        int[] popularitas = {210, 1730, 4500, 390};
        JRadioButton[] radioButtons = {borobudurButton, kutaButton, bromoButton, tobaButton};

        for (int i = 0; i < popularitas.length - 1; i++) {
            for (int j = 0; j < popularitas.length - i - 1; j++) {
                if (popularitas[j] < popularitas[j + 1]) {

                    int tempPopularitas = popularitas[j];
                    popularitas[j] = popularitas[j + 1];
                    popularitas[j + 1] = tempPopularitas;

                    String tempNama = nama[j];
                    nama[j] = nama[j + 1];
                    nama[j + 1] = tempNama;

                    int tempHarga = harga[j];
                    harga[j] = harga[j + 1];
                    harga[j + 1] = tempHarga;
                }
            }
        }
        for (int i = 0; i < radioButtons.length; i++) {
            radioButtons[i].setText(nama[i] + "     " + popularitas[i] + " pengunjung");
        }
    }//GEN-LAST:event_sortPopulerActionPerformed

    private void sortHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortHargaActionPerformed
        String[] nama = {"Candi Borobudur", "Pantai Kuta", "Gunung Bromo", "Danau Toba"};
        int[] harga = {75000, 50000, 80000, 60000};
        int[] popularitas = {2, 1, 4, 3};
        JRadioButton[] radioButtons = {borobudurButton, kutaButton, bromoButton, tobaButton};

        for (int i = 0; i < harga.length - 1; i++) {
            for (int j = 0; j < harga.length - i - 1; j++) {
                if (harga[j] > harga[j + 1]) {

                    int tempH = harga[j];
                    harga[j] = harga[j + 1];
                    harga[j + 1] = tempH;

                    String tempN = nama[j];
                    nama[j] = nama[j + 1];
                    nama[j + 1] = tempN;

                    int tempP = popularitas[j];
                    popularitas[j] = popularitas[j + 1];
                    popularitas[j + 1] = tempP;
                }
            }
        }
        for (int i = 0; i < radioButtons.length; i++) {
            radioButtons[i].setText(nama[i] + "    @Rp" + harga[i]);
        }
    }//GEN-LAST:event_sortHargaActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar dari layar check out?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new mainFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        int hasil = 0;
        if (borobudurButton.isSelected()) {
            hasil = hitung(75000, (Integer) jmlTiketSpinner.getValue());
        } else if (kutaButton.isSelected()) {
            hasil = hitung(50000, (Integer) jmlTiketSpinner.getValue());
        } else if (bromoButton.isSelected()) {
            hasil = hitung(80000, (Integer) jmlTiketSpinner.getValue());
        } else if (tobaButton.isSelected()) {
            hasil = hitung(60000, (Integer) jmlTiketSpinner.getValue());
        } else {
            JOptionPane.showMessageDialog(this, "Mohon pilih satu wisata yang diinginkan.");
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Apakah Anda sudah yakin dengan pesanan Anda?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            notaArea.setText("***************************************\n");
            notaArea.setText(notaArea.getText() + "*            Nota Pembelian Anda         *\n");
            notaArea.setText(notaArea.getText() + "***************************************\n");
            notaArea.setText(notaArea.getText() + "Total Tiket " + jmlTiketSpinner.getValue() + "\n\n");
            notaArea.setText(notaArea.getText() + "Total Harga\nRp" + hasil + " \n");
            notaArea.setText(notaArea.getText() + "***************************************\n");
            notaArea.setText(notaArea.getText() + "* Selamat Menikmati Liburan Anda! *\n");
        }
    }//GEN-LAST:event_pesanButtonActionPerformed

    private int hitung(int harga, int jmlTiket) {
        if (jmlTiket == 1) {
            return harga;
        }
        return harga + hitung(harga, jmlTiket - 1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkOutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton borobudurButton;
    private javax.swing.JRadioButton bromoButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem cariButton;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jmlTiketSpinner;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JRadioButton kutaButton;
    private javax.swing.JTextArea notaArea;
    private javax.swing.JButton pesanButton;
    private javax.swing.JButton sortHarga;
    private javax.swing.JButton sortPopuler;
    private javax.swing.JRadioButton tobaButton;
    // End of variables declaration//GEN-END:variables
}
