/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO LOQ
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pinPoinBorobudur = new javax.swing.JLabel();
        borobudurPin = new javax.swing.JPanel();

        borobudurPin.setVisible(false)
        ;
        jLabel3 = new javax.swing.JLabel();
        bromoPin = new javax.swing.JPanel();

        bromoPin.setVisible(false)
        ;
        jLabel4 = new javax.swing.JLabel();
        pinPoinKuta = new javax.swing.JLabel();
        pinPoinToba = new javax.swing.JLabel();
        tobaPin = new javax.swing.JPanel();

        tobaPin.setVisible(false)
        ;
        jLabel7 = new javax.swing.JLabel();
        kutaPin = new javax.swing.JPanel();

        kutaPin.setVisible(false)
        ;
        jLabel5 = new javax.swing.JLabel();
        pinPoinBromo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        keluar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        cariButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(25, 133, 161));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/JelajahKu Header.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pinPoinBorobudur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map pin.png"))); // NOI18N
        pinPoinBorobudur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pinPoinBorobudurMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pinPoinBorobudurMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pinPoinBorobudurMousePressed(evt);
            }
        });
        jPanel1.add(pinPoinBorobudur, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        borobudurPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 133, 161), 2));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/borobudurPin.png"))); // NOI18N

        javax.swing.GroupLayout borobudurPinLayout = new javax.swing.GroupLayout(borobudurPin);
        borobudurPin.setLayout(borobudurPinLayout);
        borobudurPinLayout.setHorizontalGroup(
            borobudurPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borobudurPinLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        borobudurPinLayout.setVerticalGroup(
            borobudurPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borobudurPinLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(borobudurPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 200, 120));

        bromoPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 133, 161), 2));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bromoPin.png"))); // NOI18N

        javax.swing.GroupLayout bromoPinLayout = new javax.swing.GroupLayout(bromoPin);
        bromoPin.setLayout(bromoPinLayout);
        bromoPinLayout.setHorizontalGroup(
            bromoPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bromoPinLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bromoPinLayout.setVerticalGroup(
            bromoPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bromoPinLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(bromoPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 200, 120));

        pinPoinKuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map pin.png"))); // NOI18N
        pinPoinKuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pinPoinKutaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pinPoinKutaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pinPoinKutaMousePressed(evt);
            }
        });
        jPanel1.add(pinPoinKuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        pinPoinToba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map pin.png"))); // NOI18N
        pinPoinToba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pinPoinTobaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pinPoinTobaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pinPoinTobaMousePressed(evt);
            }
        });
        jPanel1.add(pinPoinToba, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        tobaPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 133, 161), 2));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tobaPin.png"))); // NOI18N

        javax.swing.GroupLayout tobaPinLayout = new javax.swing.GroupLayout(tobaPin);
        tobaPin.setLayout(tobaPinLayout);
        tobaPinLayout.setHorizontalGroup(
            tobaPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobaPinLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        tobaPinLayout.setVerticalGroup(
            tobaPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tobaPinLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(tobaPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 200, 120));

        kutaPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 133, 161), 2));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kutaPin.png"))); // NOI18N

        javax.swing.GroupLayout kutaPinLayout = new javax.swing.GroupLayout(kutaPin);
        kutaPin.setLayout(kutaPinLayout);
        kutaPinLayout.setHorizontalGroup(
            kutaPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kutaPinLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kutaPinLayout.setVerticalGroup(
            kutaPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kutaPinLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(kutaPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 200, 120));

        pinPoinBromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map pin.png"))); // NOI18N
        pinPoinBromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pinPoinBromoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pinPoinBromoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pinPoinBromoMousePressed(evt);
            }
        });
        jPanel1.add(pinPoinBromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/peta indoensia.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Menu");

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu1.add(keluar);

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        cariButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cariButton.setText("Search");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });
        jMenu1.add(cariButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new LogRegFrame().setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pinPoinBromoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinBromoMouseEntered
        bromoPin.setVisible(true);
    }//GEN-LAST:event_pinPoinBromoMouseEntered

    private void pinPoinBromoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinBromoMousePressed
        new bromoFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pinPoinBromoMousePressed

    private void pinPoinBromoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinBromoMouseExited
        bromoPin.setVisible(false);
    }//GEN-LAST:event_pinPoinBromoMouseExited

    private void pinPoinBorobudurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinBorobudurMouseEntered
        borobudurPin.setVisible(true);
    }//GEN-LAST:event_pinPoinBorobudurMouseEntered

    private void pinPoinBorobudurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinBorobudurMouseExited
        borobudurPin.setVisible(false);
    }//GEN-LAST:event_pinPoinBorobudurMouseExited

    private void pinPoinBorobudurMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinBorobudurMousePressed
        new borobudurFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pinPoinBorobudurMousePressed

    private void pinPoinKutaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinKutaMouseEntered
        kutaPin.setVisible(true);

    }//GEN-LAST:event_pinPoinKutaMouseEntered

    private void pinPoinKutaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinKutaMouseExited
        kutaPin.setVisible(false);

    }//GEN-LAST:event_pinPoinKutaMouseExited

    private void pinPoinKutaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinKutaMousePressed
        new kutaFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pinPoinKutaMousePressed

    private void pinPoinTobaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinTobaMouseEntered
        tobaPin.setVisible(true);

    }//GEN-LAST:event_pinPoinTobaMouseEntered

    private void pinPoinTobaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinTobaMouseExited
        tobaPin.setVisible(false);

    }//GEN-LAST:event_pinPoinTobaMouseExited

    private void pinPoinTobaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinPoinTobaMousePressed
        new tobaFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pinPoinTobaMousePressed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        String[] wisata = {"pantai kuta", "kuta",
            "gunung bromo", "bromo",
            "candi borobudur", "borobudur",
            "danau toba", "toba"};

        String cariWisata = JOptionPane.showInputDialog(this, "Masukkan wisata yang ingin dicari");

        if (cariWisata == null || cariWisata.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon isi kolom.");
            return;
        }

        String temu = "";

        for (int i = 0; i < wisata.length; i++) {
            if (cariWisata.equalsIgnoreCase(wisata[i])) {
                temu = wisata[i];
                break;
            }
        }

        if (temu.equalsIgnoreCase(wisata[0]) || temu.equalsIgnoreCase(wisata[1])) {
            new kutaFrame().setVisible(true);
            this.setVisible(false);
        } else if (temu.equalsIgnoreCase(wisata[2]) || temu.equalsIgnoreCase(wisata[3])) {
            new bromoFrame().setVisible(true);
            this.setVisible(false);
        } else if (temu.equalsIgnoreCase(wisata[4]) || temu.equalsIgnoreCase(wisata[5])) {
            new borobudurFrame().setVisible(true);
            this.setVisible(false);
        } else if (temu.equalsIgnoreCase(wisata[6]) || temu.equalsIgnoreCase(wisata[7])) {
            new tobaFrame().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Maaf wisata yang Anda cari tidak dapat ditemukan.");
        }

    }//GEN-LAST:event_cariButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel borobudurPin;
    private javax.swing.JPanel bromoPin;
    private javax.swing.JMenuItem cariButton;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JPanel kutaPin;
    private javax.swing.JLabel pinPoinBorobudur;
    private javax.swing.JLabel pinPoinBromo;
    private javax.swing.JLabel pinPoinKuta;
    private javax.swing.JLabel pinPoinToba;
    private javax.swing.JPanel tobaPin;
    // End of variables declaration//GEN-END:variables
}
